### PR TITLE
Ptitloup/bugfix db errors

### PR DESCRIPTION
**Pull request by ptitloup**
to make it work with mysql, I change the lms_course_context field to charfield with 255 max length.
I replace the migration file number 005 with the new one and launch this two commands : 
$> python manage.py migrate lti_provider zero
$> python manage.py migrate lti_provider

regards

### CODE REVIEW

**Comment by sdreher** [comment]
Many thanks for the PR. The model change looks good. For the migration, instead of modifying an existing patch, can you use `./manage.py makemigrations` to create a new one that reflects the `max_length` change?

The [Django migration system](https://docs.djangoproject.com/en/2.0/topics/migrations/) is designed for each migration to be executed in order. Modifying existing migrations can leave databases out-of-synch with the models. Example: In our production systems, the `0005` has already run. If the PR were merged as is, we'd receive warnings that our database structure does not match the model structure.

**Comment by nikolas** [comment]
What version of MySQL are you using? It should support Django's [TextField](https://docs.djangoproject.com/en/2.0/ref/models/fields/#textfield) type, I don't think we need to change this to a CharField. You can also give TextField a max_length attribute if necessary.

**Comment by ptitloup** [comment]
Your welcome for this PR.
I tried to add a new migration (006) but the previous one didn't work and stop the migration. That's why I decided to remove it add replace it by this one.

**Comment by sdreher** [comment]
@nikolas - see this for more info: https://github.com/ccnmtl/django-lti-provider/issues/105. Looks like the unique=True is what's requiring the need for a keyLength on the MySQL end.

**Comment by nikolas** [comment]
I see - yeah, I guess a CharField would make sense then, I overlooked that we're using `unique=True` here.

**Comment by ptitloup** [comment]
I have MySQL 5.5.58.
I started by testing with textfield and max length but it didn't work that's why I change the field.
Maybe i did it to quickly...

**Comment by sdreher** [comment]
Per [doc](https://docs.djangoproject.com/en/2.0/ref/models/fields/#textfield), TextField theoretically can be used with the `max_length` attribute. Let's definitely try that before moving to a `CharField`.

**Comment by nikolas** [comment]
It also mentions that:
> If you specify a max_length attribute, it will be reflected in the Textarea widget of the auto-generated form field. However it is not enforced at the model or database level. Use a CharField for that.

So.. it it might not have any effect at the database level.

**Comment by ptitloup** [comment]
@sdreher : I can check it again
@nikolas : Yes precisly I tried this and it changed nothing

**Comment by ptitloup** [comment]
see : https://github.com/ccnmtl/django-lti-provider/pull/106/commits/eee49cb66f1aefc13cd392bcc582384de7e3d4b2

**Comment by sdreher** [comment]
Ah, good catch @nikolas. Cool - so @ptitloup - does the CharField work? And, if it does, can you create a new migration file for the change?

**Comment by ptitloup** [comment]
Yes, it seems to work. The migrations pass succesfully. This PR allready contains the charfield in the 005 migration file. Is-ti good for you ?

**Comment by sdreher** [comment]
@ptitloup - Per earlier comments, instead of modifying an existing patch, can you use `./manage.py makemigrations` to create a new migration file that reflects the CharField change?

**Comment by ptitloup** [comment]
Hello Susan, I will try to do this quickly and I keep you informed

**Comment by ptitloup** [comment]
Susan, I tried to send you a new version of my PR. (I had some trouble with git due to a command error)
I'm sorry but if I keep your migration file, it doesn't work with mysql.
May be, I can send you a new version with the models file change and the 0005 file change.
Keep me informed
Regards 
Nicolas

**Comment by ptitloup** [comment]
Done, all checks have passed...

**Comment by sdreher** [comment]
@ptitloup - Excellent. The patch looks clean. Thank you for your help!

**Pull request merged**
